# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🧶 start

on:
  workflow_dispatch:
inputs:
  org:
    description: 'GitHub Organization'
    required: true
  repo:
    description: 'GitHub Repository'
    required: true
  limit:
    description: 'Max stargazers to fetch'
    required: false
    default: 1000
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: start \
          --org ${{ inputs.org }} \
          --repo ${{ inputs.repo }} \
          --limit ${{ inputs.limit }} \
          --token ${{ secrets.GH_TOKEN }}

