# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🧶 start

on:
  workflow_dispatch:
env:
  org: github
  repo: gh-valet
  token: $${{ secrets.GH_TOKEN }}
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: start --org ${{ env.org }} --repo ${{ env.repo }} --token ${{ env.token }}
