name: 🌟 StarGazer Report

on:
  workflow_dispatch:
    inputs:
      org:
        description: "GitHub Organization"
        required: true
      repo:
        description: "GitHub Repository"
        required: true
      limit:
        description: "Max stargazers to fetch"
        required: false
        default: "10000"

jobs:
  report-cargo:
    name: 🌟 StarGazer Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --org ${{ github.events.inputs.org }} --repo ${{ github.events.inputs.repo }} --limit ${{ github.events.inputs.limit }} --token ${{ secrets.GH_TOKEN }} >> $GITHUB_STEP_SUMMARY
